/**
 * Service Worker registration.
 *
 * Registers the SW generated by vite-plugin-pwa.
 * Provides callbacks for update detection and status reporting.
 */

interface SWStatus {
  registered: boolean;
  updated: boolean;
  offline: boolean;
}

type StatusListener = (status: SWStatus) => void;

let currentStatus: SWStatus = {
  registered: false,
  updated: false,
  offline: !navigator.onLine,
};

const listeners = new Set<StatusListener>();

/** Subscribe to SW status changes. Returns unsubscribe function. */
export function onSWStatusChange(fn: StatusListener): () => void {
  listeners.add(fn);
  fn({ ...currentStatus });
  return () => listeners.delete(fn);
}

/** Get current SW status snapshot. */
export function getSWStatus(): SWStatus {
  return { ...currentStatus };
}

/** Register the service worker. Call once on app startup. */
export async function registerSW(): Promise<void> {
  if (!("serviceWorker" in navigator)) {
    console.warn("Service workers not supported in this browser.");
    return;
  }

  // Listen for online/offline changes
  window.addEventListener("online", () => {
    currentStatus.offline = false;
    notifyListeners();
  });
  window.addEventListener("offline", () => {
    currentStatus.offline = true;
    notifyListeners();
  });

  try {
    // The service worker file is generated by vite-plugin-pwa at /sw.js
    const registration = await navigator.serviceWorker.register("/sw.js", {
      scope: "/",
    });

    currentStatus.registered = true;
    notifyListeners();

    // Check for updates when the SW detects a new version
    registration.addEventListener("updatefound", () => {
      const installing = registration.installing;
      if (!installing) return;

      installing.addEventListener("statechange", () => {
        if (
          installing.state === "installed" &&
          navigator.serviceWorker.controller
        ) {
          // New SW installed but waiting — update available
          currentStatus.updated = true;
          notifyListeners();
        }
      });
    });

    // If the waiting SW activates, reload to apply
    let refreshing = false;
    navigator.serviceWorker.addEventListener("controllerchange", () => {
      if (refreshing) return;
      refreshing = true;
      window.location.reload();
    });
  } catch (err) {
    console.error("Service worker registration failed:", err);
    // App still works — just not offline
  }
}

function notifyListeners(): void {
  const snapshot = { ...currentStatus };
  for (const fn of listeners) {
    fn(snapshot);
  }
}
