/**
 * Service Worker registration.
 *
 * Registers the SW generated by vite-plugin-pwa.
 * Provides callbacks for update detection and status reporting.
 */

export interface SWStatus {
  registered: boolean;
  updated: boolean;
  offline: boolean;
  installable: boolean;
}

type StatusListener = (status: SWStatus) => void;

let currentStatus: SWStatus = {
  registered: false,
  updated: false,
  offline: !navigator.onLine,
  installable: false,
};

const listeners = new Set<StatusListener>();

let deferredPrompt: any = null;
let swRegistration: ServiceWorkerRegistration | null = null;

/** Get the deferred installation prompt event. */
export function getDeferredPrompt(): any {
  return deferredPrompt;
}

/** Clear the deferred installation prompt event. */
export function clearDeferredPrompt(): void {
  deferredPrompt = null;
  currentStatus.installable = false;
  notifyListeners();
}

/** Trigger service worker activation from a waiting state. */
export function triggerSWUpdate(): void {
  if (swRegistration && swRegistration.waiting) {
    swRegistration.waiting.postMessage({ type: "SKIP_WAITING" });
  }
}

/** Subscribe to SW status changes. Returns unsubscribe function. */
export function onSWStatusChange(fn: StatusListener): () => void {
  listeners.add(fn);
  fn({ ...currentStatus });
  return () => listeners.delete(fn);
}

/** Get current SW status snapshot. */
export function getSWStatus(): SWStatus {
  return { ...currentStatus };
}

/** Register the service worker. Call once on app startup. */
export async function registerSW(): Promise<void> {
  // Capture beforeinstallprompt before SW checking
  window.addEventListener("beforeinstallprompt", (e) => {
    e.preventDefault();
    deferredPrompt = e;
    currentStatus.installable = true;
    notifyListeners();
  });

  if (!("serviceWorker" in navigator)) {
    console.warn("Service workers not supported in this browser.");
    return;
  }

  // Listen for online/offline changes
  window.addEventListener("online", () => {
    currentStatus.offline = false;
    notifyListeners();
  });
  window.addEventListener("offline", () => {
    currentStatus.offline = true;
    notifyListeners();
  });

  try {
    // The service worker file is generated by vite-plugin-pwa at [BASE_URL]/sw.js
    const swPath = `${import.meta.env.BASE_URL}sw.js`;
    const scope = import.meta.env.BASE_URL;
    const registration = await navigator.serviceWorker.register(swPath, {
      scope,
    });
    swRegistration = registration;

    currentStatus.registered = true;

    // Check if there is already a waiting SW on load
    if (registration.waiting) {
      currentStatus.updated = true;
    }
    notifyListeners();

    // Check for updates when the SW detects a new version
    registration.addEventListener("updatefound", () => {
      const installing = registration.installing;
      if (!installing) return;

      installing.addEventListener("statechange", () => {
        if (
          installing.state === "installed" &&
          navigator.serviceWorker.controller
        ) {
          // New SW installed but waiting — update available
          currentStatus.updated = true;
          notifyListeners();
        }
      });
    });

    // If the waiting SW activates, reload to apply
    let refreshing = false;
    navigator.serviceWorker.addEventListener("controllerchange", () => {
      if (refreshing) return;
      refreshing = true;
      window.location.reload();
    });
  } catch (err) {
    console.error("Service worker registration failed:", err);
    // App still works — just not offline
  }
}

function notifyListeners(): void {
  const snapshot = { ...currentStatus };
  for (const fn of listeners) {
    fn(snapshot);
  }
}
